### ISSUE TITLE
Yaml formatting

### ISSUE THREAD

**Issue by nicosantangelo** [NicoSantangelo/sublime-text-i18n-rails#6]
Right now, when a key is added or edited, the yaml file gets sorted in alphabetical order and quotes are deleted. For example:

From this:

``` yaml
en:
  test:
    new: "Bye"
    index:
      few: "Hello"
```

to this:

``` yaml
en:
  test:
    index:
      few: Hello
    new: Bye
```
