### ISSUE TITLE
Cleaning up of yml file contents on incorrect key nesting

### ISSUE THREAD

**Issue by jastkand** [NicoSantangelo/sublime-text-i18n-rails#8]
The yml file we have:

```
en:
  titles:
    home: Home Page
    gallery: Gallery
  greeting:
    hello: Hello world
```

If we try to add translation with key `t('greeting')` than all the contents of `yml` file will be cleaned up. It made me a little bit disappointed for a while.
